version: "3"

services: 
    db: 
      image: postgres
      container_name: tasksdb
      environment: 
        POSTGRES_PASSWORD: tasks
        POSTGRES_DB: tasks
      expose: 
        - 5432
      ports: 
        - 5432:5432

    api:
      image: biojj/tasks-api
      container_name: tasks-api
      expose: 
        - 3333
      ports: 
       - 3333:3333
      depends_on: 
       - "db"

networks: 
    default:
      driver: bridge