version: "3"

services: 
    db: 
      image: postgres
      container_name: tasksdb
      environment: 
        POSTGRES_PASSWORD: tasks
        POSTGRES_DB: tasks
      expose: 
        - 5432
      ports: 
        - 5432:5432

    api:
      image: biojj/task-api
      container_name: task-api
      expose: 
        - 3333
      ports: 
       - 3333:3333
      depends_on: 
       - "db"

    web:
    image: biojj/task-web
    container_name: task-web 
    
    ports: 
      - "3000:3000"
    depends_on: 
      - api

networks: 
    default:
      driver: bridge